
services:
  app:
    image: node-rest-api:v1.0.1
    build: 
      context: .
      dockerfile: Dockerfile
    user: appuser
    container_name: node-rest-api-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.app
